server:
  port: ${port.codebox-web}

spring:
  profiles:
    active: local
  boot:
    admin:
      client:
        url: http://codebox-boot-admin
        instance:
          name: Codebox Web Service :${spring.application.name}
          service-base-url: http://codebox-boot-admin:${server.port}
        username: admin
        password: test
        enabled: true
  banner:
    location: classpath:/banner/banner.txt

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  profiles: local
  boot:
    admin:
      client:
        url: http://127.0.0.1:${port.codebox-boot-admin}
        instance:
          name: Codebox Web Service :${spring.application.name}
          service-base-url: http://127.0.0.1:${server.port}
          username: admin
          password: test
          enabled: true


---
spring:
  profiles: dev


---
spring:
  profiles: stag


---
spring:
  profiles: prod