server:
  port: ${port.codebox-web}

spring:
  application:
    name: codebox-web
  profiles:
    active: local
  config:
    import: "optional:configserver:http://codebox-cloud-config"
  boot:
    admin:
      client:
        url: http://codebox-boot-admin
        instance:
          name: CodeBox Web Service :${spring.application.name}
          service-base-url: http://codebox-boot-admin:${server.port}
        username: admin
        password: test
        enabled: true
  banner:
    location: classpath:/banner/banner.txt

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  config:
    activate:
      on-profile: local
    import: "optional:configserver:http://127.0.0.1:8500"
  boot:
    admin:
      client:
        url: http://127.0.0.1:${port.codebox-boot-admin}
        instance:
          name: CodeBox Web Service :${spring.application.name}
          service-base-url: http://127.0.0.1:${server.port}
        username: admin
        password: test
        enabled: true

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stag

---
spring:
  config:
    activate:
      on-profile: prod